### ISSUE TITLE
Why you do this work

### ISSUE THREAD

**Issue by AnTao97** [pqhieu/torch3d#8]
Someone has already done many works in https://github.com/rusty1s/pytorch_geometric, so I just wondering what is the difference between your git and rusty1s/pytorch_geometric. Also, both of the two gits do not provide reimplementation results to validate their code.

**Comment by pqhieu** [comment]
Thank you for your interest. Please refer to #3 where I gave a comparison to PyTorch Geometric.

The point of this reimplementation is not for replicating the **exact same** results from papers, since different papers may used different dataset preprocessing, augmentation, or validation to push the numbers. However, I did test my reimplementation and get similar results. Your point about publishing reimplementation results is still valid and I will add them in the description later.

**Comment by AnTao97** [comment]
However, I do find your reimplementations have some mistakes, and I happen to have done some works before. 

DGCNN: Your code for DGCNN in segmentation task lacks spacial transform network and categorical vector input. Also, the paper adopts k=40 in the end, not k=20. I have already reimplement DGCNN in my git https://github.com/AnTao97/dgcnn and get below results.
![屏幕快照 2020-01-24 下午6 16 48](https://user-images.githubusercontent.com/41320807/73061708-c4447b80-3ed5-11ea-9afa-83f44178ccc9.png)

FoldingNet: Your encoder lacks local covariance network and graph layer. I have already reimplement FoldingNet in my git https://github.com/AnTao97/UnsupervisedPointCloudReconstruction and get the same result in FoldingNet paper.

If you find my gits useful, please give clear indication.

I suggest you do a thorough research before writing your code. Nevertheless, I'm still looking forward to your finished library.
